### ISSUE TITLE
Configuration for 3rd party plugins.

### ISSUE THREAD

**Issue by Greedquest** [python-lsp/python-lsp-server#129]
I'm slightly confused. I want to use `pylsp-mypy` to give me warnings in a jupyter notebook in jupyter lab. I made a conda environment for all the bits and pieces:

```
conda create -n jup python>=3.8 jupyterlab nb_conda_kernels jupyterlab_lsp python-lsp-server
```

Then added mypy language server extension listed in your [recommended 3rd party plugins](https://github.com/python-lsp/python-lsp-server#3rd-party-plugins)
```
conda install -n jup -c conda-forge pylsp-mypy
```
.... but then what? The jupyter-lsp docs give some indication about configuring a language server:

    // pylsp: {
    //   serverSettings: {
    //     "pylsp.plugins.pydocstyle.enabled": true,
    //     "pylsp.plugins.pyflakes.enabled": false,
    //     "pylsp.plugins.flake8.enabled": true
    //   }
    // }

Which seems to match up with what is in https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md. But that's only got entries for the included plugins, not all the 3rd party ones (ofc that makes sense, they are 3rd party after all). How do I configure mypy to be enabled in the python-lsp-server?

**Comment by ccordoba12** [comment]
This is not a question we can answer here because it's about how to configure the JupyterLab LSP client.

So, please reopen this issue in

https://github.com/jupyter-lsp/jupyterlab-lsp

**Comment by Greedquest** [comment]
@ccordoba12 sorry, I may ask there but I felt this is more a question of how to configure the python-lsp-server per the content for ./CONFIGURATION.MD in this repo. Jupyter is just how I happen to be calling it, but I'm confused about which options to configure the python server with, not how to enter those options in the jupyter lab settings menu. Or do you still think I should ask there?

**Comment by ccordoba12** [comment]
> I may ask there but I felt this is more a question of how to configure the python-lsp-server per the content for ./CONFIGURATION.MD in this repo

Ok, so there are two things about this:

1. Those options only apply to the plugins distributed as part of this server (i.e. the ones in https://github.com/python-lsp/python-lsp-server/tree/develop/pylsp/plugins).
2. The server provides those options but can't set them. In other words, it sets the default values listed in CONFIGURATION.md when started but after that it can't change any by itself. Instead, clients need to send requests asking to modify those values.

You also asked

> Then added mypy language server extension listed in your recommended 3rd party plugins
>
> conda install -n jup -c conda-forge pylsp-mypy
>
> .... but then what?

You need to restart the PyLSP server (or JupyterLab if the client doesn't provide an option to do that) so that it can pick up the new plugin. After that, you shouldn't need to do anything else, i.e. you should see linting provided by MyPy in the notebook.

Also, pylsp-mypy provides the following config options, but I'm unsure how to change them from the JupyterLab client:

https://github.com/Richardk2n/pylsp-mypy#configuration

For that, please request for help on the repo I referenced above.

**Comment by Greedquest** [comment]
@ccordoba12  Thank you so much that's really helpful
