### ISSUE TITLE
Disable rule with inline comment

### ISSUE THREAD

**Issue by MarcelRobitaille** [python-lsp/python-lsp-server#166]
First of all, thank you for this amazing LSP server

I would like to disable certain rules with inline comments. For example, with pylint, I can add `# pylint: disable=import-error` at the end of a line to disable that linting error for only that specific line. Is there anything like that with this language server?

**Comment by ccordoba12** [comment]
Hey @MarcelRobitaille, thanks for reporting. By default, this server uses Pyflakes for linting, which doesn't offer this functionality. If you want to have it, you need to disable that plugin and enable the Pylint plugin instead.

In order to do that, you need to send a didChangeConfiguration request from your client to the server. Since that depends on your client (i.e. Neovim, Sublime, Emacs, etc), you need to ask how to do that in its repo or forums.
