### ISSUE TITLE
Conflict between README and CONFIGURATION

### ISSUE THREAD

**Issue by doolio** [python-lsp/python-lsp-server#263]
The [README](https://github.com/python-lsp/python-lsp-server#configuration) states when configuring flake8 one must 

> 3. Change the pylsp.configurationSources setting (in the value passed in from your client) to ['flake8'] in order to use the flake8 configuration instead.

However, the [CONFIGURATION](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md#python-language-server-configuration) suggests the value is either `["pycodestyle"]` or `["pyflakes"]`.

Which document is correct? I set it to `["flake8"]` and it seems to work. Thanks for your time.

**Comment by krassowski** [comment]
Thanks for opening an issue. `flake8` clearly should have been included (see test case in https://github.com/python-lsp/python-lsp-server/blob/fa27a2be2b95a039432cf8f1f60179b44f811798/test/plugins/test_flake8_lint.py#L99 and https://github.com/python-lsp/python-lsp-server/blob/98dc9c090e7da2c6584653b228ea6fdf26172388/pylsp/config/config.py#L53

It is however not clear to me if `pyflakes` should be there; there is no config source for those (unless it comes from a plugin):

https://github.com/python-lsp/python-lsp-server/blob/98dc9c090e7da2c6584653b228ea6fdf26172388/pylsp/config/config.py#L50-L60

**Comment by doolio** [comment]
> It is however not clear to me if pyflakes should be there; there is no config source for those (unless it comes from a plugin):

True but maybe there should be considering `flake8` is just a wrapper around `pyflakes` (which is really the error checker), `pycodestyle` and `mccabe` (plus others if also available such as `pydocstyle` (with `flake8-docstrings`), `pep8-naming` etc.).

That is perhaps `pylsp.configurationSources` should accept all three possibilities:
- `["pyflakes"]` if you only want to check for code errors
- `["pycodestyle"]` if you only want to check for style errors
- `["flake8"]` if you want to check for both plus the added ability to check for complexity (via `mccabe`), docstrings (via `pydocstyle + flake8-docstrings`), PEP8 naming (via `pep8-naming`) etc.

**Comment by doolio** [comment]
Any further thoughts on this?

**Comment by rchl** [comment]
I think the whole situation with `configurationSources` has derailed a bit.

Here me out.
It seems like introducing `pylsp.configurationSources` was a misguided decision (at least for flake8) as flake8 can and will read the relevant configuration files itself, regardless of that setting.

The `pylsp.configurationSources` might have been introduced because someone realized that some of the configuration settings, specifically ones that depend on file path/name, do not work. That is because the files are linted through stdin and flake8 is not aware of actual file path.

So someone added custom code to read the settings in flake8 pylsp plugin and apply those settings to linted files. So now we have a `pylsp.configurationSources` setting that is only really relevant for some of the settings but for other is not even needed.

The proper solution IMO would be to just make flake8 aware of the actual file path by using the `--stdin-display-name` argument that it supports. It can be set to an actual path so that all the rules that work based on file path can work properly.

(I might be missing something as I'm not a big user of flake8 but I was thinking about it yesterday)

**Comment by ccordoba12** [comment]
> The proper solution IMO would be to just make flake8 aware of the actual file path by using the --stdin-display-name argument that it supports. It can be set to an actual path so that all the rules that work based on file path can work properly.

Thanks for analyzing the situation in depth @rchl. Could you create a pull request that implements your proposed solution?

**Comment by rchl** [comment]
> > The proper solution IMO would be to just make flake8 aware of the actual file path by using the --stdin-display-name argument that it supports. It can be set to an actual path so that all the rules that work based on file path can work properly.
> 
> Thanks for analyzing the situation in depth @rchl. Could you create a pull request that implements your proposed solution?

Maybe I'd do that if I had more time but would still not be sure what extent of changes is expected here. Whether removing the `flake8` form `pylsp.configurationSources` and all related code that manually reads the configuration would be OK or not.

**Comment by ccordoba12** [comment]
> Whether removing the flake8 form pylsp.configurationSources and all related code that manually reads the configuration would be OK or not.

If it's not really necessary, then I'm +1 with doing that.
