### ISSUE TITLE
Error due to mistakenly detected "circular import"

### ISSUE THREAD

**Issue by zzhuolun** [python-lsp/python-lsp-server#287]
# Problem statement
Hi, I'm using pylsp with neovim and [neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig). I'm constantly encountering the problem of "client x quit with exit code 1 and signal 0" when I try to jump to definition of symbols.

# Cause of the problem
When I check the :LspLog, the log shows the following error:
![image](https://user-images.githubusercontent.com/23330740/199469117-506bc04d-8702-4ea5-8f02-c18e53e0b6f0.png)

The log says that the error comes from circuluar import, thought it actually is not a circular import : 

the types.py in my python package folder (`~/miniconda3/envs/new-pigan/lib/python3.9/site-packages/pytorch3d/implicitron/dataset/types.py`) is not the python built in types.py. When `import types`, the python built in types.py should be imported but the lsp seems to think the types should be the `types.py` of a python package (in this case the `pytorch3d` package, which caused the error.

After I renamed the `~/miniconda3/envs/new-pigan/lib/python3.9/site-packages/pytorch3d/implicitron/dataset/types.py`, this error went away, but another similar error came up:

![image](https://user-images.githubusercontent.com/23330740/199471758-16c6ae41-5d0c-478d-9fb8-fab50227928f.png)

Apparently at `import math`, the `math` should be the python built in `math` module, however pylsp refers it again as the `/usr/stud/zhouzh/miniconda3/envs/new-pigan/lib/python3.9/site-packages/pytorch3d/transforms/math.py' in the python package.

# My configurations
- NVIM v0.8.0
- nvim-lspcofig
```
local lspconfig = require('lspconfig')
local lsp_defaults = lspconfig.util.default_config

lsp_defaults.capabilities = vim.tbl_deep_extend(
  'force',
  lsp_defaults.capabilities,
  require('cmp_nvim_lsp').default_capabilities()
)

-- LSP servers
require'lspconfig'.pylsp.setup{
    -- on_attach = on_attach,
    -- flags = lsp_flags,
        settings = {
    pylsp = {
      plugins = {
        pycodestyle = {
          ignore = {'W391'},
          maxLineLength = 100
        }
      }
    }
  }
}
```
- python-language-server 0.36.2
- python-lsp-server      1.5.0

**Comment by ccordoba12** [comment]
Hey @zzhuolun, thanks for reporting. This problem seems to be related to the current working directory used by Neovim to start the server. In Spyder we avoid that issue by making the server start in a hidden, empty directory where no one can install Python packages.

However, it seems in your case the server is started in `/miniconda3/envs/new-pigan/lib/python3.9/site-packages/pytorch3d`, and that's why it fails. Another possibility could be that you're adding that directory to your `PYTHONPATH`, which is a really bad practice.

**Comment by zzhuolun** [comment]
> Hey @zzhuolun, thanks for reporting. This problem seems to be related to the current working directory used by Neovim to start the server. In Spyder we avoid that issue by making the server start in a hidden, empty directory where no one can install Python packages.
> 
> However, it seems in your case the server is started in `/miniconda3/envs/new-pigan/lib/python3.9/site-packages/pytorch3d`, and that's why it fails. Another possibility could be that you're adding that directory to your `PYTHONPATH`, which is a really bad practice.

Hey @ccordoba12 , thanks so much for your reply!

I used `vim.fn.getcwd()` to print out the current working directory and it returns my project folder, which is expected. And my `$PYTHONPATH` returns an empty list. 

I used another virtual environ `pigan` without this `pytorch3d` package in another project folder and encountered similar issues: when I tried to jump to definitions of symbols, the error occured after two jumps:
![image](https://user-images.githubusercontent.com/23330740/200199722-378be08d-1cb4-42dd-9d81-9c418778e69a.png)

Obviously, at `from types import MappingProxyType, DynamicClassAttribute`, the types should be referred to as the `python3.9/types.py`, while the lsp seems to jump to the types of `torch/types.py` and caused the error.

I also print the :LspInfo
![image](https://user-images.githubusercontent.com/23330740/200199826-e981d707-6bdc-4856-8e11-d665067d032b.png)

**Comment by ccordoba12** [comment]
> I used vim.fn.getcwd() to print out the current working directory and it returns my project folder, which is expected

Ok, but I don't think that's the same directory used to start the server because I'd expect them to be different. Since I don't use Neovim, I don't know how to look for that.

> And my $PYTHONPATH returns an empty list.

Ok, that's bad but it was going to be my next suggestion.

Anyhow, I don't know how else to help you, but I'm almost sure the errors you're getting are not related to this project but to something in your configuration or Neovim. So my recommendation is for you to keep looking for something fishy.
