### ISSUE TITLE
List of allowed values for pylsp.plugins.pydocstyle.convention in CONFIGURATION.md incorrect

### ISSUE THREAD

**Issue by doolio** [python-lsp/python-lsp-server#292]
The [CONFIGURATION](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md) suggests possible string values for `pylsp.plugins.pydocstyle.convention` are `"pep257"`, `"numpy"`, and `"None"` but [the official documentation states](https://www.pydocstyle.org/en/stable/error_codes.html#default-conventions) the allowed values are in fact `"pep257"`, `"numpy"`, and `"google"`.

**Comment by krassowski** [comment]
"google" is only available since version 4.0.0 (https://www.pydocstyle.org/en/stable/release_notes.html#july-6th-2019) does pylsp already support it?

Edit: it seems the answer is yes, so the enum should be updated:

https://github.com/python-lsp/python-lsp-server/blob/b24ffd3939e35b3db8e45d06bf51b177c456574b/pyproject.toml#L34

**Comment by doolio** [comment]
OK, PR #295 submitted for consideration.
