### ISSUE TITLE
Plugin for `ruff` for linting (and eventually formatting?)

### ISSUE THREAD

**Issue by jhossbach** [python-lsp/python-lsp-server#299]
I recently came upon [ruff](https://github.com/charliermarsh/ruff) which provides a very fast alternative to flake8 written in Rust. It implements all (or most) of the flake8 rules as well as various flake8 plugins with a serious increase of speed.
The plan for this is to eventually plan establish their own LSP but I was wondering if you are interested in a plugin for linting as an alternative to flake8. I am willing to create a pull request if there is some interest.

**Comment by ccordoba12** [comment]
Hey @jhossbach, thanks for the suggestion! Sure, we're interested in having a plugin for Ruff because it's a very interesting project with a lot of potential.

> I am willing to create a pull request if there is some interest.

Nice! Looking forward to review it.

**Comment by charliermarsh** [comment]
Let me know if I can be helpful, or if you run into any questions or issues with the interface.

**Comment by krassowski** [comment]
Big +1 from me too. Potential packaging concerns aside this sounds great! Two questions:
- Does `ruff` expose precise start/end positions? We hit a wall with this for flake/pyflakes  (#253).
- Would the integration run in watch mode, or start a new instance each time?

**Comment by charliermarsh** [comment]
Yeah! Ruff exposes a precise start and end position for all checks. (I'm sure the granularity of those spans could be improved in some cases, but they exist for all checks and improving them is something I'm happy to invest in as those cases come up.)

I think it'd be fine to invoke Ruff every time rather than running in watch mode, since watch mode is more useful for monitoring file changes -- but in this case, I'm guessing change events would come from the LSP?

**Comment by ccordoba12** [comment]
> but in this case, I'm guessing change events would come from the LSP?

No, LSP's don't have a monitoring mechanism. That needs to be provided by clients.

**Comment by charliermarsh** [comment]
Sorry, that was just sloppy terminology. What I meant to say is that Ruff doesn't need to handle file-watching in this case, right? That it'll be invoked by the LSP at the appropriate times?

**Comment by ccordoba12** [comment]
Oh yeah, that's correct. Clients send a `textDocument/didChange` request when a file changes on their side, which triggers linting automatically afterwards here.

**Comment by jhossbach** [comment]
Currently working on the plugin, I read through #27 but am unsure as to what the naming convention should be from now on. I personally like `python-lsp-ruff`, or should `pylsp-ruff` be used instead?

**Comment by jhossbach** [comment]
Also, I am unfamiliar with the `kind` type given by ruff, can you help on that @charliermarsh?

**Comment by charliermarsh** [comment]
@jhossbach - `kind` is the enum defined [here](https://github.com/charliermarsh/ruff/blob/d699bb7b86eace469a25a7f6a280ee7d091c4c93/src/checks.rs#L417) -- it's basically the plain-text name for the check (as opposed to `code`, which is an identifier like `F841`). The serialization of `kind` is a bit odd because it's an enum, so it sometimes has extra, anonymous fields included as a list. I actually removed `kind` from the JSON output recently for that reason, so you probably want to use `code` instead?

**Comment by ccordoba12** [comment]
> I personally like python-lsp-ruff, or should pylsp-ruff be used instead?

`python-lsp-ruff` sounds good to me because it'd go very well with [`python-lsp-black`](https://github.com/python-lsp/python-lsp-black).

@jhossbach, would you like to host your plugin in our organization? I think it'd be nice, but of course it's up to you.

**Comment by jhossbach** [comment]
> 
> @jhossbach, would you like to host your plugin in our organization? I think it'd be nice, but of course it's up to you.

Great idea, do I have to be invited to the organization in order to create a new repo there?

**Comment by ccordoba12** [comment]
> Great idea, do I have to be invited to the organization in order to create a new repo there?

Yep, I just sent you an invite. After you accept it, you could create your repo here.

**Comment by jhossbach** [comment]
Great! I'll create the repo as soon as I get it working locally.

**Comment by jhossbach** [comment]
Closing as completed, you can find the new plugin here: https://github.com/python-lsp/python-lsp-ruff

**Comment by charliermarsh** [comment]
Thanks for all your work on this @jhossbach!

**Comment by jhossbach** [comment]
> Thanks for all your work on this @jhossbach!

Happy to contribute :)
