### ISSUE TITLE
Enabling rope-autoimport by default

### ISSUE THREAD

**Issue by bagel897** [python-lsp/python-lsp-server#356]
I was wondering if we should enable it by default. Otherwise, what blockers/testing would we need to clear before we can?
As I remember, the issue we were nervous about was ``should_insert`` logic. How much usage of autoimport have we seen so far?

**Comment by ccordoba12** [comment]
I don't know if it's a good idea to enable autoimport by default. The thing is it can be annoying and/or disconcerting to see your editor adding new code that you didn't explicitly asked for.

For people that like autoimport or think it's really useful, that's fine. But since it's an opt-in feature, they shouldn't have a problem with the way things work now. However, newbies or casual users could have a hard time understanding what autoimport does and adapting their workflows to it.

**Comment by bagel897** [comment]
That's perfectly reasonable, just wanted to make sure there's no development work on my end here.

**Comment by ccordoba12** [comment]
Thanks for understanding @bagel897!
