### ISSUE TITLE
How do I configure the python version that the code is written for?

### ISSUE THREAD

**Issue by palandovalex** [python-lsp/python-lsp-server#398]
I use my home pc to develop, bun on server has lower version of interpretter. Can i strictly set pylsp to use python 3.8 insted of python 3.10?

**Comment by ccordoba12** [comment]
Hey @palandovalex, I think the only way to do that is for you to use a virtual environment with the Python version you want to use, install this server on that env, start it with the `--host` and `--port` options and then connect your editor/IDE to it. The last step depends on your editor/IDE, so we can't provide more details about it.

Otherwise, pylsp will use the Python version of the env in which it's installed.

Let us know if that was helpful.
